# Generated by Django 5.1.6 on 2025-02-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terno',
            name='descricao',
            field=models.TextField(default=1, max_length=100, verbose_name='Texto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terno',
            name='titulo',
            field=models.CharField(default=1, max_length=20, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
