# Generated by Django 5.1.6 on 2025-02-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_terno_descricao_terno_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terno',
            name='img',
            field=models.ImageField(upload_to='produtos/', verbose_name='Imagem 1'),
        ),
    ]
