# Generated by Django 5.0 on 2025-04-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_tamanho_terno_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sapato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Texto')),
                ('cor', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='produtos/sapato', verbose_name='Imagem 1')),
            ],
        ),
    ]
