# Generated by Django 5.1.6 on 2025-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_terno_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo')),
                ('descricao', models.TextField(max_length=100, verbose_name='Texto')),
                ('img', models.ImageField(upload_to='produtos/infantil', verbose_name='Imagem 1')),
            ],
        ),
    ]
