# Generated by Django 5.0 on 2025-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_sapato'),
    ]

    operations = [
        migrations.AddField(
            model_name='sapato',
            name='tamanho',
            field=models.IntegerField(choices=[(37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43)], default=1),
            preserve_default=False,
        ),
    ]
