# Generated by Django 5.0 on 2025-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_infantil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamnho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='terno',
            name='tamanho',
            field=models.ManyToManyField(related_name='produtos', to='produtos.tamnho'),
        ),
    ]
