# Generated by Django 5.0 on 2025-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_sapato_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=100, null=True, verbose_name='Texto')),
                ('cor', models.CharField(max_length=20)),
                ('tamanho', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])),
                ('img', models.ImageField(upload_to='produtos/camisas', verbose_name='Imagem 1')),
            ],
        ),
    ]
