# Generated by Django 5.0 on 2025-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terno',
            name='descricao',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Texto'),
        ),
    ]
