# Generated by Django 5.0 on 2025-09-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_terno_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camisa',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='camisa',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='infantil',
            name='descricao',
            field=models.TextField(max_length=250, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='infantil',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='sapato',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sapato',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='sapato',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='terno',
            name='descricao',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='terno',
            name='titulo',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
