# Generated by Django 5.0 on 2025-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acessorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessorios',
            name='img',
            field=models.ImageField(default=1, upload_to='acessorios/', verbose_name='Imagem 1'),
            preserve_default=False,
        ),
    ]
